import { useEffect, useRef, useState } from "react"
import { BookOpen, CircleSlash, Send, Sparkles } from "lucide-react"
import { toast } from "sonner"

import { Disclaimer } from "@/components/disclaimer"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Empty, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupTextarea,
} from "@/components/ui/input-group"
import { Spinner } from "@/components/ui/spinner"
import { api, ApiError } from "@/lib/api"
import type { RagAnswer, RagStatus } from "@/lib/types"

const EXAMPLES = [
  "What must be declared as the retail sale price on a pre-packaged commodity?",
  "How should the month and year of manufacture be shown?",
  "What are the minimum height requirements for the declarations?",
  "Which packages are exempt from the packaged commodities rules?",
]

type Turn = { question: string; answer: RagAnswer | null; error?: string }

export function AskPage() {
  const [status, setStatus] = useState<RagStatus | null>(null)
  const [question, setQuestion] = useState("")
  const [turns, setTurns] = useState<Turn[]>([])
  const [busy, setBusy] = useState(false)
  const endRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    api.ragStatus().then(setStatus).catch(() => setStatus(null))
  }, [])

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: "smooth" })
  }, [turns, busy])

  async function ask(text: string) {
    const query = text.trim()
    if (!query || busy) return
    setBusy(true)
    setQuestion("")
    setTurns((current) => [...current, { question: query, answer: null }])
    try {
      const answer = await api.ask({ query, k: 5 })
      setTurns((current) =>
        current.map((turn, i) => (i === current.length - 1 ? { ...turn, answer } : turn)),
      )
    } catch (error) {
      const message =
        error instanceof ApiError ? error.message : "Could not reach the compliance API"
      setTurns((current) =>
        current.map((turn, i) =>
          i === current.length - 1 ? { ...turn, error: message } : turn,
        ),
      )
      toast.error(message)
    } finally {
      setBusy(false)
    }
  }

  return (
    <div className="mx-auto flex w-full max-w-4xl flex-col gap-6 px-4 py-8">
      <header className="flex flex-col gap-2">
        <h1 className="text-3xl font-semibold tracking-tight">Ask the rules</h1>
        <p className="text-muted-foreground">
          Questions are answered from the indexed Legal Metrology corpus, with the
          clauses that support the answer. When retrieval finds nothing solid, the
          system says so instead of composing statutory-sounding prose.
        </p>
        {status && (
          <div className="flex flex-wrap items-center gap-2 pt-1">
            <Badge variant="secondary">{status.corpus.chunks} clauses indexed</Badge>
            <Badge variant="outline">
              {status.generator === "groq"
                ? `Generated by ${status.generation_model}`
                : "Extractive answers (no language model configured)"}
            </Badge>
            {status.reranker_model && <Badge variant="outline">Cross-encoder rerank</Badge>}
            <Badge variant="outline">No web search</Badge>
          </div>
        )}
      </header>

      {turns.length === 0 && (
        <Empty>
          <EmptyHeader>
            <EmptyMedia variant="icon">
              <Sparkles />
            </EmptyMedia>
            <EmptyTitle>Ask a question about packaged-commodity labelling</EmptyTitle>
            <EmptyDescription>Try one of these to start.</EmptyDescription>
          </EmptyHeader>
          <div className="flex flex-col gap-2">
            {EXAMPLES.map((example) => (
              <Button
                key={example}
                variant="outline"
                size="sm"
                className="h-auto py-2 text-left whitespace-normal"
                onClick={() => ask(example)}
              >
                {example}
              </Button>
            ))}
          </div>
        </Empty>
      )}

      <div className="flex flex-col gap-6">
        {turns.map((turn, index) => (
          <div key={index} className="flex flex-col gap-3">
            <div className="bg-muted ml-auto max-w-[85%] rounded-lg px-4 py-2.5 text-sm">
              {turn.question}
            </div>
            {turn.error ? (
              <Alert variant="destructive">
                <AlertTitle>Could not answer</AlertTitle>
                <AlertDescription>{turn.error}</AlertDescription>
              </Alert>
            ) : turn.answer ? (
              <AnswerCard answer={turn.answer} />
            ) : (
              <Card>
                <CardContent className="text-muted-foreground flex items-center gap-3 py-6 text-sm">
                  <Spinner />
                  Searching the regulation corpus…
                </CardContent>
              </Card>
            )}
          </div>
        ))}
        <div ref={endRef} />
      </div>

      <div className="bg-background sticky bottom-4">
        <InputGroup>
          <InputGroupTextarea
            placeholder="Ask about a declaration, an exemption, a date format…"
            value={question}
            rows={2}
            onChange={(e) => setQuestion(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault()
                ask(question)
              }
            }}
          />
          <InputGroupAddon align="block-end">
            <span className="text-muted-foreground text-xs">
              Enter to send, Shift+Enter for a new line
            </span>
            <InputGroupButton
              className="ml-auto"
              disabled={busy || !question.trim()}
              onClick={() => ask(question)}
            >
              {busy ? <Spinner data-icon /> : <Send />}
              Ask
            </InputGroupButton>
          </InputGroupAddon>
        </InputGroup>
      </div>

      <Disclaimer />
    </div>
  )
}

function AnswerCard({ answer }: { answer: RagAnswer }) {
  // A greeting, or a question about this tool, is not a failed lookup. Showing
  // it in the refusal card would tell the reader the corpus was searched and
  // came up short, which is not what happened.
  if (answer.intent !== "regulation") {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="text-primary size-5" />
            {answer.intent === "capability" ? "About this assistant" : "Ask me about the rules"}
          </CardTitle>
        </CardHeader>
        <CardContent className="text-sm leading-relaxed whitespace-pre-wrap">
          {answer.answer}
        </CardContent>
      </Card>
    )
  }

  if (!answer.grounded) {
    return (
      <Card className="border-amber-600/30">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <CircleSlash className="text-amber-600" />
            Not answered
          </CardTitle>
          <CardDescription>{answer.answer}</CardDescription>
        </CardHeader>
        {answer.sources.length > 0 && (
          <CardContent>
            <p className="text-muted-foreground mb-3 text-sm">
              The closest clauses retrieved, for you to judge yourself:
            </p>
            <SourceList sources={answer.sources} />
          </CardContent>
        )}
      </Card>
    )
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex flex-wrap items-center gap-2">
          <CardTitle>Answer</CardTitle>
          <Badge variant="secondary">
            {Math.round(answer.confidence * 100)}% retrieval confidence
          </Badge>
          <Badge variant="outline">
            {answer.generator === "groq" ? "language model" : "verbatim extract"}
          </Badge>
          {answer.reranked && <Badge variant="outline">reranked</Badge>}
        </div>
      </CardHeader>
      <CardContent className="flex flex-col gap-5">
        <div className="text-sm leading-relaxed whitespace-pre-wrap">{answer.answer}</div>
        <div>
          <h3 className="mb-2 flex items-center gap-2 text-sm font-medium">
            <BookOpen className="size-4" />
            Sources ({answer.sources.length})
          </h3>
          <SourceList sources={answer.sources} />
        </div>
      </CardContent>
    </Card>
  )
}

function SourceList({ sources }: { sources: RagAnswer["sources"] }) {
  return (
    <Accordion type="multiple">
      {sources.map((source) => (
        <AccordionItem key={source.chunk_id} value={source.chunk_id}>
          <AccordionTrigger>
            <span className="flex flex-wrap items-center gap-2 text-left">
              <span className="font-mono text-xs">{source.metadata.rule}</span>
              <span>{source.metadata.title}</span>
              <Badge variant="secondary" className="tabular-nums">
                {source.score.toFixed(2)}
              </Badge>
            </span>
          </AccordionTrigger>
          <AccordionContent className="flex flex-col gap-3">
            <blockquote className="border-l-2 pl-3 text-sm">{source.content}</blockquote>
            <p className="text-muted-foreground text-xs">
              {source.metadata.document}
              {source.metadata.page ? ` · page ${source.metadata.page}` : ""}
              {source.metadata.verified ? " · verified against the source document" : ""}
            </p>
            <dl className="text-muted-foreground grid grid-cols-2 gap-x-4 gap-y-1 text-xs sm:grid-cols-4">
              <ScoreRow label="Keyword" value={source.scores.keyword} />
              <ScoreRow label="Vector" value={source.scores.vector} />
              <ScoreRow label="Hybrid" value={source.scores.hybrid} />
              <ScoreRow label="Rank fusion" value={source.scores.rrf} />
            </dl>
          </AccordionContent>
        </AccordionItem>
      ))}
    </Accordion>
  )
}

function ScoreRow({ label, value }: { label: string; value: number | null | undefined }) {
  return (
    <div className="flex justify-between gap-2">
      <dt>{label}</dt>
      <dd className="tabular-nums">
        {typeof value === "number" ? value.toFixed(3) : "—"}
      </dd>
    </div>
  )
}
